### ISSUE TITLE
banner image size issue

### ISSUE THREAD

**Issue by yodelheck** [jessykate/modernomad#218]
Suggestion:
 in the edit location>content blocks section, change the helper text for the image upload to suggest 800x225 pixels 

Explanation:
the img div ("location-img-preview") that the banner fits into on the locations page is 800x225 which is a different aspect ratio and causes stretching.  I uploaded one at 800x225 and it looks pimp. (this is for canopy)

**Comment by jessykate** [comment]
i dig it @yodelheck!
