### ISSUE TITLE
CSS on event page is a little broken at ~990px width

### ISSUE THREAD

**Issue by derekrazo** [jessykate/modernomad#237]
![screen shot 2015-06-05 at 12 10 03 pm](https://cloud.githubusercontent.com/assets/3849179/7997076/e218fbe6-0b7b-11e5-9999-d184e28db3ca.png)

Just a little thing!

**Comment by jessykate** [comment]
yeesh, that sucks. will look at that.

**Comment by jessykate** [comment]
this should be closed by commit 7f1c11c
