### ISSUE TITLE
Login should redirect to the originating page

### ISSUE THREAD

**Issue by stefansjs** [jessykate/modernomad#252]
This is totally not high urgency (but might be a nice entry point for a new-to-the-project developer such as myself *wink wink*).

It would be nice if logging into the embassy network didn't redirect to the generic embassy network page, but went to the page from which the user logged in.

The use case is simple:
go to redvic.com
click login
get redirected to embassynetwork.com => It would be nice to be redirected to redvic.embassynetwork.com

**Comment by jessykate** [comment]
YES! Would definitely take a pull request for this! It used to do that but
I think recent changes broke it again.

Don't forget to check out the trello board also! It is more current and
should be public, but we can definitely use github issues for intake as
well.

Trello is linked from the contributing page I think, and also listed in the
topic of the #modernomad channel on embassy network slack.



On Thursday, December 10, 2015, stefansjs <notifications@github.com> wrote:

> This is totally not high urgency (but might be a nice entry point for a
> new-to-the-project developer such as myself *wink wink*).
>
> It would be nice if logging into the embassy network didn't redirect to
> the generic embassy network page, but went to the page from which the user
> logged in.
>
> The use case is simple:
> go to redvic.com
> click login
> get redirected to embassynetwork.com => It would be nice to be redirected
> to redvic.embassynetwork.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jessykate/modernomad/issues/252>.
>


-- 
Jessy Kate Schingler
http://jessykate.com

**Comment by stefansjs** [comment]
Oh, ok. The contributing page told me to look at github issues for feature requests.

Any insight on where I should start looking in the code?

**Comment by jessykate** [comment]
I think maybe core/viewsnot near the bottom is a lot of the login logic.:).

Jacob is also very familiar with it and reachable through the slack
channel.

On Thursday, December 10, 2015, stefansjs <notifications@github.com> wrote:

> Oh, ok. The contributing page told me to look at github issues for feature
> requests.
>
> Any insight on where I should start looking in the code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jessykate/modernomad/issues/252#issuecomment-163460975>
> .
>


-- 
Jessy Kate Schingler
http://jessykate.com

**Comment by jsayles** [comment]
I'm not able to reproduce the problem.  and I'm a little confused.

What I'm seeing is:

go to http://redvic.com
immediately redirected to https://embassynetwork.com/locations/redvic/
click login
goes to https://embassynetwork.com/people/login/?next=/locations/redvic/
login
back to https://embassynetwork.com/locations/redvic/

Your use case implies you are going about this a little differently and I need more information to see it how you see it.

**Comment by kgstew** [comment]
Odd. Login always takes me to https://embassynetwork.com/people/login/ with
no next property in the URL.

After login im redirected to https://embassynetwork.com



Kyle Stewart
kgstew@gmail.com
Skype: kgstew
(303) 579-8047

**Comment by stefansjs** [comment]
Oh, thanks Jacob, I found the difference. There's two "login" buttons. One is in the top-right corner of the page, to the right of "Add your Community" and behaves as it should. The other is next to About, Stay, Events, People, ...

If you click that one, there is no next property, and no redirect after logging in.

**Comment by jsayles** [comment]
Well that's an easy fix!  I'll push this live and we'll be set.  Thank you.
